import {Poppins} from 'next/font/google';
import "./globals.css";
import ReactQueryClientProvider from "./provider/QueryClientProvider";

const poppins_init = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['300','400','500', '600', '700'],
})

export const metadata = {
  title: "THETICKET.COM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins_init.className} antialiased`}>
        <ReactQueryClientProvider>
          {children}
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
